name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - master # Cambia a la rama que uses

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Instalar dependencias
        run: npm install

      - name: Construir la aplicación
        run: npm run build

      - name: Desplegar a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: dist
